# Generated by Django 5.2.11 on 2026-02-22 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('colour_hex', models.CharField(default='#6c757d', help_text='Hex colour used for UI badges (e.g. #ff5733).', max_length=7)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the artwork (2–255 characters).', max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(help_text='A short description of the artwork (min 10 characters).', validators=[django.core.validators.MinLengthValidator(10)])),
                ('year_created', models.PositiveIntegerField(help_text='Year the artwork was created.', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2026)])),
                ('medium', models.CharField(help_text='Materials used (e.g. Oil on canvas, Bronze, Watercolour).', max_length=150)),
                ('dimensions', models.CharField(blank=True, help_text='Optional dimensions (e.g. 73 × 92 cm).', max_length=100)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated market value in USD.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.URLField(blank=True, help_text='Optional URL to an image of the artwork.')),
                ('is_on_display', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(help_text='The artist who created this piece.', on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='artists.artist')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='artworks.category')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-year_created', 'title'],
            },
        ),
    ]
