# Generated by Django 5.2.11 on 2026-02-22 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Exhibition title (3–255 characters).', max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('tagline', models.CharField(blank=True, help_text='A short promotional tagline.', max_length=300)),
                ('description', models.TextField(help_text='Full description of the exhibition (min 20 characters).', validators=[django.core.validators.MinLengthValidator(20)])),
                ('location', models.CharField(help_text='Gallery room or external venue.', max_length=200)),
                ('start_date', models.DateField(help_text='Opening date of the exhibition.')),
                ('end_date', models.DateField(help_text='Closing date of the exhibition.')),
                ('cover_image_url', models.URLField(blank=True, help_text='Optional URL to a banner/cover image.')),
                ('admission_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Admission price in USD. Enter 0 for free events.', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this exhibition from the public listing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artworks', models.ManyToManyField(blank=True, help_text='Select the artworks featured in this exhibition.', related_name='exhibitions', to='artworks.artwork')),
            ],
            options={
                'verbose_name': 'Exhibition',
                'verbose_name_plural': 'Exhibitions',
                'ordering': ['-start_date'],
            },
        ),
    ]
