# Generated by Django 5.2.11 on 2026-02-22 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the artist (2–200 characters).', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('nationality', models.CharField(choices=[('American', 'American'), ('British', 'British'), ('French', 'French'), ('German', 'German'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Dutch', 'Dutch'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Russian', 'Russian'), ('Other', 'Other')], default='Other', max_length=50)),
                ('birth_year', models.PositiveIntegerField(help_text='Four-digit birth year.', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2026)])),
                ('death_year', models.PositiveIntegerField(blank=True, help_text='Leave blank if the artist is still alive.', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2026)])),
                ('biography', models.TextField(help_text='A short biography (minimum 20 characters).', validators=[django.core.validators.MinLengthValidator(20)])),
                ('profile_image_url', models.URLField(blank=True, help_text="Optional URL to the artist's profile image.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['name'],
            },
        ),
    ]
